### ISSUE TITLE
Use Cases Opschrijven

### ISSUE THREAD

**Issue by BramSikkens** [SoftwareProject2-groep6/Java-Applicatie#16]
# Opstellen van de use cases 

### Wat bevat de use cases?

- Een omschrijving van wat de use case doet.

- Een succes scenario

- Een faal scenario 

_Je kan de reeds gemaakte useCase terugvinden op_:  https://ehb.instructure.com/groups/1613/files?preview=29296

**Comment by TijlMuys** [comment]
- [Beheren van Training ] 
- [Inschrijven van Training] 
- [Opvragen van gegevens en Statistieken] 
- [Invullen van Survey] 
- [Bestellen van boeken] 

https://ehb.instructure.com/groups/1613/files/folder/Analyse/Use%20Cases
