### ISSUE TITLE
Activity diagrams maken 

### ISSUE THREAD

**Issue by BramSikkens** [SoftwareProject2-groep6/Java-Applicatie#19]

**Comment by BramSikkens** [comment]
# Voorbeeld Activity Diagrams

<img width="376" alt="screen shot 2017-10-10 at 13 59 43" src="https://user-images.githubusercontent.com/16198438/31385387-5fb15f76-adc3-11e7-8f82-639551624a45.png">

**Comment by TijlMuys** [comment]
Ik heb een aantal aanpassingen gemaakt aan de activity diagrams van Dylan vermits deze gemaakt waren op basis van de nog niet aangepaste Use Cases. Enkele termen heb ik hernoemd...
