### ISSUE TITLE
Weergeven van boeken op TrainingPagina

### ISSUE THREAD

**Issue by BramSikkens** [SoftwareProject2-groep6/Java-Applicatie#68]
Op elke specifieke TrainingsPagina wordt het nodige cursusmateriaal weergegeven

**Comment by TijlMuys** [comment]
Welke dao gingen we voor de boeken gebruiken, die van google? Ik veronderstel dat we met ISBN-nummer de boeken aangeven, dan kunnen we deze boeken doorverwijzen naar de google API...

**Comment by BramSikkens** [comment]
Ja, Google Books.
Die hebben ook een API
